### ISSUE TITLE
Screenshots are broken for the floating_search_bar README

### ISSUE THREAD

**Issue by teolemon** [rodydavis/floating_search_bar#1]
Screenshots are broken for the floating_search_bar README

https://github.com/rodydavis/floating_search_bar/tree/60721e4e90618138cb1ca20680469fc95c646a5a

**Comment by rodydavis** [comment]
Thanks for the Issue! This is now fixed on the latest version. I also added an online demo: https://rodydavis.github.io/floating_search_bar/#/
